/**
 * 서버 에러 코드. docs/decisions/010-api-response-contract.md 의 레지스트리와 1:1로 대응한다.
 *
 * 분기는 이 code로만 한다. 서버가 주는 message 문자열로 분기하지 않는다.
 * 문구는 예고 없이 바뀔 수 있다.
 */
export const ErrorCode = {
  INVALID_INPUT: 'COMMON_001',
  INVALID_JSON: 'COMMON_002',
  INVALID_CURSOR: 'COMMON_003',
  TOO_MANY_REQUESTS: 'COMMON_004',
  INTERNAL_ERROR: 'COMMON_999',
  RESOURCE_NOT_FOUND: 'RESOURCE_001',

  UNAUTHORIZED: 'AUTH_001',
  FORBIDDEN: 'AUTH_002',
  DUPLICATE_EMAIL: 'AUTH_003',
  INVALID_CREDENTIALS: 'AUTH_004',
  INVALID_REFRESH_TOKEN: 'AUTH_005',
  TOO_MANY_LOGIN_ATTEMPTS: 'AUTH_006',
  MALFORMED_JWT: 'AUTH_007',
  USER_NOT_FOUND: 'USER_001',

  INVALID_BLOG_URL: 'BLOG_001',
  BLOCKED_BLOG_URL: 'BLOG_002',
  BLOG_NOT_REACHABLE: 'BLOG_003',
  BLOG_NOT_SUPPORTED: 'BLOG_004',
  BLOG_LOOKUP_EXPIRED: 'BLOG_005',
  TOO_MANY_LOOKUP_REQUESTS: 'BLOG_006',

  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_001',
  ALREADY_SUBSCRIBED: 'SUBSCRIPTION_002',

  POST_NOT_FOUND: 'POST_001',

  OWNERSHIP_NOT_FOUND: 'OWNERSHIP_001',
  BLOG_ALREADY_OWNED: 'OWNERSHIP_002',
  USER_ALREADY_OWNS_BLOG: 'OWNERSHIP_003',
  VERIFICATION_NOT_FOUND: 'OWNERSHIP_004',
  VERIFICATION_EXPIRED: 'OWNERSHIP_005',
  VERIFICATION_CODE_NOT_FOUND: 'OWNERSHIP_006',
  TOO_MANY_VERIFICATION_ATTEMPTS: 'OWNERSHIP_007',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
