spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  auth:
    refresh-cookie-secure: true

logging:
  level:
    com.blogzip: DEBUG
